[project]
name = "url-shorter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.0",
]

[project.scripts]
dev = "url_shorter.main:run"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "ruff>=0.16.1",
]

